name: Build Solution

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # OVO JE NOVI KORAK KOJI TI FALI
      - name: Restore NuGet Packages
        run: nuget restore ZastitaInformacija.sln

      - name: Build Solution
        run: msbuild ZastitaInformacija.sln /p:Configuration=Release /p:AdditionalIncludeDirectories=include