name: Build and Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages
        run: nuget restore ZastitaInformacija.sln

      - name: Build Solution (Release)
        run: msbuild ZastitaInformacija.sln /p:Configuration=Release /p:AdditionalIncludeDirectories=include

      - name: Run Performance Benchmark
        shell: cmd
        run: |
          echo --- RUNNING AUTOMATED PERFORMANCE TESTS ---
          .\x64\Release\ZastitaInformacija.exe --benchmark